{% set version = "0.1.0" %}
{% set name = "pywin32-on-windows" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [not win]

requirements:
  host:
    - python
  run:
    - python
    - pywin32

test:
  imports:
    - win32api
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mhammond/pywin32
  doc_url: https://github.com/mhammond/pywin32
  dev_url: https://github.com/mhammond/pywin32
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A virtual package for pywin32... but only on windows'
  description: |
    This package exists so other packages can depend on `pywin32`, often the only
    platform specific dependency, while remaining `noarch: python`. On non-Windows
    platforms, installing it is a no-op.
extra:
  recipe-maintainers:
    - bollwyvl
    - Arishamays1
